#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Echo.Resource", IsApplication=true)]

namespace Echo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blog_black = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blog_white = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int left = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int news_black = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int news_white = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int people_black = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int people_white = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int right = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int show_black = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int show_white = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int blogAuthor = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int blogDate = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int blogId = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int blogTitle = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int main_content = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int newsDate = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int newsId = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int newsTitle = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int pager = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int recycler_view = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int textView1 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int toolbar = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int toolbar_top = 2131165188;
			
			// aapt resource value: 0x7f07000e
			public const int top_menu_blog = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int top_menu_news = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int top_menu_show = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BlogCardView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NewsCardView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int tab = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int toolbar = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int top_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int author = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int blog = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int calendar = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int news = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int next = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int previous = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int show = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
